cmake_minimum_required(VERSION 3.30)
project(BankAccountAssignment)

set(CMAKE_CXX_STANDARD 20)

add_executable(BankAccountAssignment main.cpp
Functional/Account.h
Functional/Account.cpp
Functional/AccountHolder.cpp
Functional/AccountHolder.h
Functional/CheckingAccount.cpp
Functional/CheckingAccount.h)

